apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: ttc-api
  namespace: monitoring
  labels:
    release: monitoring

spec:
  namespaceSelector:
    matchNames:
      - ttc-monitor

  selector:
    matchLabels:
      app: ttc-api

  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
