apiVersion: v1
kind: Pod
metadata:
  name: ttc-ingest
  namespace: ttc-monitor

spec:
  restartPolicy: Never

  imagePullSecrets:
    - name: ghcr-secret

  containers:
    - name: ingestion
      image: ghcr.io/jorge-ma/ttc-reliability-v2-api:0.1.0
      imagePullPolicy: Always

      command:
        - sleep
        - "3600"

      env:
        - name: POSTGRES_HOST
          value: postgres

        - name: POSTGRES_PORT
          value: "5432"

        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_DB

        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_USER

        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
