apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-nfs-pv
spec:
  capacity:
    storage: 5Gi

  accessModes:
    - ReadWriteOnce

  persistentVolumeReclaimPolicy: Retain

  storageClassName: synology-nfs

  mountOptions:
    - hard
    - nfsvers=4.1

  nfs:
    server: 10.10.10.199
    path: /volume2/k8s-postgres/postgres-data

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data-nfs
  namespace: ttc-monitor
spec:
  accessModes:
    - ReadWriteOnce

  storageClassName: synology-nfs

  resources:
    requests:
      storage: 5Gi


