"""create ingestion and delay event tables

Revision ID: 325af7668703
Revises: 
Create Date: 2026-09-09 10:34:18.215473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '325af7668703'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_file', sa.String(length=255), nullable=False),
    sa.Column('source_rows', sa.Integer(), nullable=False),
    sa.Column('valid_rows', sa.Integer(), nullable=False),
    sa.Column('rejected_rows', sa.Integer(), nullable=False),
    sa.Column('duplicate_rows', sa.Integer(), nullable=False),
    sa.Column('inserted_rows', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='running', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('running', 'completed', 'failed')", name='ck_ingestion_status'),
    sa.CheckConstraint('duplicate_rows >= 0', name='ck_ingestion_duplicate_rows'),
    sa.CheckConstraint('inserted_rows >= 0', name='ck_ingestion_inserted_rows'),
    sa.CheckConstraint('rejected_rows >= 0', name='ck_ingestion_rejected_rows'),
    sa.CheckConstraint('source_rows >= 0', name='ck_ingestion_source_rows'),
    sa.CheckConstraint('valid_rows >= 0', name='ck_ingestion_valid_rows'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('delay_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingestion_run_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.Column('day', sa.String(length=9), nullable=False),
    sa.Column('station', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('min_delay', sa.Integer(), nullable=False),
    sa.Column('min_gap', sa.Integer(), nullable=False),
    sa.Column('bound', sa.String(length=20), nullable=False),
    sa.Column('line', sa.String(length=20), nullable=False),
    sa.Column('vehicle', sa.Integer(), nullable=False),
    sa.Column('event_datetime', sa.DateTime(), nullable=False),
    sa.Column('record_key', sa.String(length=64), nullable=False),
    sa.CheckConstraint('min_delay >= 0', name='ck_delay_min_delay'),
    sa.CheckConstraint('min_gap >= 0', name='ck_delay_min_gap'),
    sa.CheckConstraint('source_id >= 0', name='ck_delay_source_id'),
    sa.CheckConstraint('vehicle >= 0', name='ck_delay_vehicle'),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['ingestion_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('record_key')
    )
    op.create_index('ix_delay_events_code', 'delay_events', ['code'], unique=False)
    op.create_index('ix_delay_events_event_datetime', 'delay_events', ['event_datetime'], unique=False)
    op.create_index(op.f('ix_delay_events_ingestion_run_id'), 'delay_events', ['ingestion_run_id'], unique=False)
    op.create_index('ix_delay_events_line', 'delay_events', ['line'], unique=False)
    op.create_index(op.f('ix_delay_events_source_id'), 'delay_events', ['source_id'], unique=False)
    op.create_index('ix_delay_events_station', 'delay_events', ['station'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_delay_events_station', table_name='delay_events')
    op.drop_index(op.f('ix_delay_events_source_id'), table_name='delay_events')
    op.drop_index('ix_delay_events_line', table_name='delay_events')
    op.drop_index(op.f('ix_delay_events_ingestion_run_id'), table_name='delay_events')
    op.drop_index('ix_delay_events_event_datetime', table_name='delay_events')
    op.drop_index('ix_delay_events_code', table_name='delay_events')
    op.drop_table('delay_events')
    op.drop_table('ingestion_runs')
    # ### end Alembic commands ###
